spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction_app
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true;
  flyway:
    user: postgres
    password: root
    schemas: auction_app
    url: jdbc:postgresql://localhost:5432/auction_app
    locations: classpath:db/migrations

configuration:
  swagger:
    app: 'Auction App'
    description: 'Auction App project'
    developer: 'Lejla Muratović'
    email: 'lejlamuratovic6@gmail.com'

security:
  jwt:
    secret: '72e4005430b4306533e93b0852df15a34f2564c5db289d03b76c9aa0c6bab7b3'
    cookieExpiry: 3600

JWT_SECURE: false