spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

configuration:
  swagger:
    app: 'Auction App'
    description: 'Auction App project'
    developer: 'Lejla Muratović'
    email: 'lejlamuratovic6@gmail.com'

