spring:
  datasource:
    url: jdbc:postgresql://dpg-cp0h51q1hbls73eaktmg-a.frankfurt-postgres.render.com/auction_app_cqgi
    username: auction_app_cqgi_user
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  flyway:
    user: auction_app_cqgi_user
    password: ${DB_PASSWORD}
    schemas: auction_app
    url: jdbc:postgresql://dpg-cp0h51q1hbls73eaktmg-a.frankfurt-postgres.render.com/auction_app_cqgi
    locations: classpath:db/migrations

configuration:
  swagger:
    app: 'Auction App'
    description: 'Auction App project'
    developer: 'Lejla Muratović'
    email: 'lejlamuratovic6@gmail.com'

security:
  jwt:
    secret: ${JWT_SECRET}

JWT_SECURE: false

cookie:
  accessExpiry: 604800000 # 7 days in milliseconds
  refreshExpiry: 604800000 # 7 days in milliseconds

amazonProperties:
  endpointUrl: https://s3.eu-central-1.amazonaws.com
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucketName: ${AWS_BUCKET_NAME}
