spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auction_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true;

  flyway:
    user: root
    password: root
    schemas: auction_app
    url: jdbc:postgresql://localhost:5432/auction_app
    locations: classpath:db/migrations

configuration:
  swagger:
    app: 'Auction App'
    description: 'Auction App project'
    developer: 'Lejla Muratović'
    email: 'lejlamuratovic6@gmail.com'

